#!/bin/bash 
convert -delay 50 00_ADD_SUPERVISOR_PASSWORD_ON_NEW_PC/*.png 00_ADD_SUPERVISOR_PASSWORD_ON_NEW_PC.mp4
convert -delay 50 -loop 1 00_ADD_SUPERVISOR_PASSWORD_ON_NEW_PC/*.png 00_ADD_SUPERVISOR_PASSWORD_ON_NEW_PC.gif
