#!/bin/bash 
convert -delay 50 18_TURN_ON_SECURE_BOOT_SETUP_MODE_ON_NEW_PC/*.png 18_TURN_ON_SECURE_BOOT_SETUP_MODE_ON_NEW_PC.mp4
convert -delay 50 -loop 1 18_TURN_ON_SECURE_BOOT_SETUP_MODE_ON_NEW_PC/*.png 18_TURN_ON_SECURE_BOOT_SETUP_MODE_ON_NEW_PC.gif
