#!/bin/bash 
convert -delay 50 20_ENABLE_SECURE_BOOT_AGAIN_ON_NEW_PC/*.png 20_ENABLE_SECURE_BOOT_AGAIN_ON_NEW_PC.mp4
convert -delay 50 -loop 1 20_ENABLE_SECURE_BOOT_AGAIN_ON_NEW_PC/*.png 20_ENABLE_SECURE_BOOT_AGAIN_ON_NEW_PC.gif
